### PR TITLE
add new position-class to center the toaster

### PR DESCRIPTION
**Pull request by Joluma**
I add three new class, `toaster-top-center`, `toaster-bottom-center` and `toaster-center`, to be able to display the toaster in the center of the screen, on top, bottom or full center.

I needed that for a project so maybe it can be usefull for other people.

### CODE REVIEW

**Comment by Mr-Anonymous** [comment]
Do you have toastr-bottom-right position? It doesnt seem be included, is it? I would prefer to show the toastr bubble in the bottom right, is that possible? Thank you jirikavi!

**Comment by Stabzs** [comment]
@Mr-Anonymous it's there.  If you check the css, you'll find: `.toast-bottom-right`. That's what you need.

**Comment by Mr-Anonymous** [comment]
hm... I couldnt get it to work when I tried that class earlier. I will recheck my code again. Thank you for confirming this!

Cheers,
Neel.

**Comment by Stabzs** [comment]
I noticed you mentioned `toastr-bottom-right`.  It is `toaster-bottom-right`.  So that could have been the issue.

**Comment by Mr-Anonymous** [comment]
I think thats it! I didint pick up on that until you mentioned it. Thank you for spotting that. Cheers!

**Comment by Stabzs** [comment]
Perfect, glad it works for you!

**Comment by Mr-Anonymous** [comment]
@Stabzs Just now I added to my code and it worked after I added the `toast-bottom-right` class. :)

Just a quick question, does it plugin have `progressBar` setting?

**Comment by Stabzs** [comment]
@Mr-Anonymous Awesome news!

No, there is no progressBar setting in AngularJS toaster currently.  If you have the time, feel free to create a pull request with the feature and the appropriate tests and I'd be happy to take a look at it and merge it in.

If you don't have the time or desire to create it, feel free to request it via a new issue and I'll take a look at it at some point when I have some time :).  It's a bit of a larger addition though so I'm not sure when I'd be able to get to it.

**Comment by Mr-Anonymous** [comment]
@Stabzs  Sure no worries... Its not a big deal without it and I dont think it will be that worth it if its a large addition increasing the code base unnecessarily. So no problem at all.

Thank you so much for your prompt replies. I tried couple of other ng-Toastr plugins that uses jquery, and out of all I find this one working best for my project. I like it how it is CCS3 based. 

Much obliged with your contribution on this. Love this addition to my project! :)

**Comment by Stabzs** [comment]
@Mr-Anonymous Happy to help and happy to contribute!  The library has been invaluable to me and I'm just trying to give back to it a little :).  Jiri did some really great work with it :).

**Pull request merged**
