### PR TITLE
Now it Will Allow User To Update Existing Messages

### PR DESCRIPTION
**Pull request by deadmann**
#249 
I update the toaster, so if user hold a reference to the toasted object, s/he can update any of the older messages... for know it only work on changing body property... and if you want time which get restarted on body change, have different value, you should set it before setting body(if it's async) i did not create the minimal toaster.js object... 

please do it through your own method

### CODE REVIEW

**Comment by Stabzs** [comment]
I'm not certain I agree with the overall approach here.

By registering an additional watch, you decrease performance for all consumers, even when they have no desire to update the toast at a future point in time.  

I'm all for allowing post-pop modifications to a toast, but I would like to see it done without an additional watcher.

**Comment by deadmann** [comment]
now user have to set this config before watcher get set:
'post-modification-ready':true

**Comment by deadmann** [comment]
I'm updating My Repository Again, Since the library i add requires more library, so i remove thouse items...

**Comment by Stabzs** [comment]
This cannot be merged.  It is unclear at this point what the scope of the change is and the coverage has decreased.  I will not merge any pull request that decreases coverage, and the intent of the change is still unclear.

**Comment by deadmann** [comment]
intent is obvious, to allow post modification
why post modification? to disallow error spamming

why not doing it in code? always keep related stuff in same class/macro/ etc. rule of OOP... and reduce redundant code
----------------------------------------------------
BTW why the coverage decrease? and what is coverage? is there any way to fix it?

**Comment by Stabzs** [comment]
I mean it is difficult to understand the current state of the code due to numerous commits adding and then removing code. 

Coverage refers to test coverage.  All pull requests adding new functionality must also add tests that test and cover the added functionality.   See https://github.com/jirikavi/AngularJS-Toaster/blob/master/test/toasterContainerSpec.js

**Comment by deadmann** [comment]
ok

**Pull request closed without merging**
