### PR TITLE
Adding posibility to send arbitrary data to templates.

### PR DESCRIPTION
**Pull request by xeor**
There is currently no way to send arbitrary data to the templates used in the toasts. The only current use of templates right now is for static data.
I really need a way to send custom data to the templates from the place that first initiate the toast.

This fix makes that possible without breaking anything.

### CODE REVIEW

**Comment by xeor** [comment]
Example-usage for sending custom data; `toaster.pop('warning', "Job done", {'template': "job-done.html", 'data': {'job-title': jobTitle}}, null, 'template');`

**Comment by xeor** [comment]
Alternatively, I can make the change a little better, and inject the data as its own parameter at the end of pop(), `.pop(.., data)`. I think  that might be better. It will look cleaner, you could reuse the templates more easiely for stuff like dropdown notification lists, you could use it in trustedHtml. Comments?

**Comment by xeor** [comment]
Looking at the toaster code, it doesnt look so easy going for plan B above using `data`  inside the toast. Hope this gets accepted as is, so at least `toast.data` will be available.

**Comment by jirikavi** [comment]
Hi,
I cannot use your PR, because it throws an error when a template is not defined...
You can fill template by data from $scope.

For instance:
template:
`<script type="text/ng-template" id="myTemplate.html">
       <p>Render a custom template! {{bar}}</p>
</script>`
in Controller:
`$scope.bar = 'Hi';`

Jiri.

**Comment by xeor** [comment]
Sorry for the PR not covering. But the change only applies if it is using a template, so I don't see why it needs to support anything else..? Am I wrong? How do you want it so it will be "ok"?

The scope wont be available, as I can see or test. The only thing I can think about is to use a service as it will be a singleton, but then again, that will be hackish and probably unstable as well if several `toasts` are in the progress.

If I am wrong, can you please provide an better example? Sending parameters to a toast template from the caller of the `pop()` function will be crucial in my usage.

**Comment by xeor** [comment]
@jirikavi I made a version that I think might work. Look at http://plnkr.co/edit/TvkHWxohNsnHL8bILnZE?p=preview where the `toaster.pop(..)` at line 12 works.
Togheter with everything else.

**Comment by jirikavi** [comment]
Hi Xeor,
Check the latest release. There is a plunk as example http://plnkr.co/edit/HKTC1a
Jiri.

**Comment by xeor** [comment]
Very cool/nice!! Thanks a lot! I will keep looking after a donate button for when/if you want a beer or 5

**Comment by jirikavi** [comment]
You are nice and I was thinking for a while that I would add the button but I read this article http://www.learn-cocos2d.com/2012/03/10-golden-rules-donate-button/ and when you are in the Czech republic we can meet and buy me a beer :)

**Pull request closed without merging**
