### PR TITLE
Added package.json

### PR DESCRIPTION
**Pull request by shwei**
For better compatibility with npm

### CODE REVIEW

**Comment by jirikavi** [comment]
Hi, Thanks for the PR!

**Comment by shwei** [comment]
You're very welcome. Please publish this wonderful module on npm repo. For more info about this, please check out https://docs.npmjs.com/getting-started/publishing-npm-packages. Thank you for working on this project!

**Comment by maxdow** [comment]
+1

**Comment by maxdow** [comment]
You should change the name in package.json to angularjs-toaster for full compatibility with npm. I published the package here https://www.npmjs.com/package/angularjs-toaster fell free to take the ownership :)

**Pull request merged**
