### PR TITLE
Useless bower.json file and added npmignore

### PR DESCRIPTION
**Pull request by maxdow**
Since this project no longer uses bower, the bower.json file is useless. I also added a npmignore file in order to don't push tests to npm repo.

### CODE REVIEW

**Comment by Stabzs** [comment]
Won't removing the bower.json file also remove the corresponding bower package from bower.io, breaking integration for those that use bower instead of non?

**Comment by maxdow** [comment]
ohhhh too bad !  so sorry i totally forgotten about the availability on bower.io.. i only was thinking about tooling . i guess this file is needed so .. can you merge just 1 commit or i have to do an other PR ?

**Comment by Stabzs** [comment]
I don't think I can select just one commit. Mind doing a new PR and I'll merge it in?

**Comment by maxdow** [comment]
yes i will do that

**Pull request closed without merging**
